### PR TITLE
Everything about tab

### PR DESCRIPTION
**Pull request by rbzgamer**

### CODE REVIEW

**Review by iambaangkok — CHANGES_REQUESTED** [review]
- Remove tabId, permission from CreateTab,EditTab Dto
- can you change the route of some GET routes with only tabName and challengeTitle so that everything is in query params instead of some in the body?
eg. 

```
 @Get('/:tabName')
    getTabByName(
        @Param('tabName') tabName: string,
        @Body() challengeTitle: string    
    )

``` 
change to `GET /:challengeTitle/:tabName`

maybe change everything that needs challengeTitle and tabName so that the route is `/:challengeTitle/:tabName`

meaning that challengeTitle in those routes' dto should be removed too

**Comment by iambaangkok** [comment]
please use relative path in imports, see dto & typeorm imports, vscode usually import those files using absolute path

**Comment by rbzgamer** [comment]
> please use relative path in imports, see dto & typeorm imports, vscode usually import those files using absolute path

got it

**Review by iambaangkok — APPROVED** [review]
Very good. High quality. Approved for merge.

**Pull request merged**
